/*

 LHS-PLAYER-STATIC.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char LHSTile[] =
{
  0xAA,0xFF,0x55,0xFF,0xAA,0xFF,0x55,0xFF,
  0xAA,0xFF,0x55,0xFF,0xAA,0xFF,0x55,0xFF
};

/* End of LHS-PLAYER-STATIC.C */
