/*

 A.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0xFF,0xFF,0xE7,0xE7,0xC3,0xC3,0xDB,0xDB,
  0x89,0x89,0xA1,0xA1,0xBD,0xBD,0xFF,0xFF
};

/* End of A.C */
