/*

 E.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0xFF,0xFF,0xE3,0xE3,0xDF,0xDF,0xBF,0xBF,
  0x83,0x83,0xBF,0xBF,0x83,0x83,0xFF,0xFF
};

/* End of E.C */
