/*

 M.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0xFF,0xFF,0xB9,0xB9,0x91,0x91,0x85,0x85,
  0xA5,0xA5,0xB5,0xB5,0xBD,0xBD,0xFF,0xFF
};

/* End of M.C */
