/*

 N.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0xFF,0xFF,0xBD,0xBD,0x9D,0x9D,0x8D,0x8D,
  0xA5,0xA5,0xB1,0xB1,0xB9,0xB9,0xFF,0xFF
};

/* End of N.C */
