/*

 S.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0xFF,0xFF,0xC7,0xC7,0xBB,0xBB,0xBF,0xBF,
  0xC3,0xC3,0xFD,0xFD,0xBD,0xBD,0x83,0x83
};

/* End of S.C */
