/*

 W.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0xFF,0xFF,0xBD,0xBD,0xBD,0xBD,0xBD,0xBD,
  0xA5,0xA5,0xD9,0xD9,0xDD,0xDD,0xFF,0xFF
};

/* End of W.C */
