/*

 X.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0xBF,0xBF,0xBF,0xBF,0x9D,0x9D,0xC9,0xC9,
  0xC7,0xC7,0x93,0x93,0xBB,0xBB,0xBF,0xBF
};

/* End of X.C */
