package dev.punchcafe.vngine.gb.codegen.render;

public interface ComponentRendererName {

    String UTILITY_METHOD_RENDERER_NAME = "UTILITY_METHOD_RENDERER";
    String MAIN_METHOD_RENDERER_NAME = "MAIN_METHOD_RENDERER";
    String SETUP_METHOD_RENDERER_NAME = "SETUP_METHOD_RENDERER";
    String NODE_MUTATION_RENDERER_NAME = "NODE_MUTATION_RENDERER";
    String TRANSITION_INITIALIZER_RENDERER_NAME = "TRANSITION_INITIALIZER_RENDERER";
    String PLAYER_TRANSITION_DEFINITION_RENDERER_NAME = "PLAYER_TRANSITION_DEFINITION_RENDERER";
    String PREDICATE_TRANSITION_DEFINITION_RENDERER_NAME = "PREDICATE_TRANSITION_DEFINITION_RENDERER";
    String NARRATIVE_DEFINITION_RENDERER_NAME = "NARRATIVE_DEFINITION_RENDERER";
    String NARRATIVE_RENDERER_NAME = "NARRATIVE_RENDERER";
    String NODE_DEFINITION_RENDERER_NAME = "NODE_DEFINITION_RENDERER";
}
