package dev.punchcafe.vngine.gb.codegen.render;

public interface ComponentRendererName {

    String UTILITY_METHOD_RENDERER_NAME = "UTILITY_METHOD_RENDERER";
    String MAIN_METHOD_RENDERER_NAME = "MAIN_METHOD_RENDERER";
    String SETUP_METHOD_RENDERER_NAME = "SETUP_METHOD_RENDERER";
    String NODE_MUTATION_RENDERER_NAME = "NODE_MUTATION_RENDERER";
    String TRANSITION_INITIALIZER_RENDERER_NAME = "TRANSITION_INITIALIZER_RENDERER";
    String PLAYER_TRANSITION_DEFINITION_RENDERER_NAME = "PLAYER_TRANSITION_DEFINITION_RENDERER";
    String PREDICATE_TRANSITION_DEFINITION_RENDERER_NAME = "PREDICATE_TRANSITION_DEFINITION_RENDERER";
    String NARRATIVE_DEFINITION_RENDERER_NAME = "NARRATIVE_DEFINITION_RENDERER";
    String NARRATIVE_RENDERER_NAME = "NARRATIVE_RENDERER";
    String NODE_DEFINITION_RENDERER_NAME = "NODE_DEFINITION_RENDERER";
    String NODE_RENDERER_NAME = "NODE_RENDERER";
    String DO_NOTHING_MUTATION_ARRAY_RENDERER_NAME = "DO_NOTHING_MUTATION_ARRAY_RENDERER";
    String BRANCH_RENDERER_NAME = "BRANCH_RENDERER";
    String ALWAYS_TRUE_PREDICATE_RENDERER_NAME = "ALWAYS_TRUE_PREDICATE_RENDERER";
    String GAME_OVER_NODE_ID_CONSTANT_RENDERER_NAME = "GAME_OVER_NODE_ID_CONSTANT_RENDERER";
    String PROMPTS_RENDERER_NAME = "PROMPTS_RENDERER";
    String GET_NEXT_NODE_FUNCTION_RENDERER_NAME = "GET_NEXT_NODE_FUNCTION_RENDERER";
    String PLAY_NARRATIVE_RENDERER_NAME = "PLAY_NARRATIVE_RENDERER";
    String CURRENT_NODE_RENDERER_NAME = "CURRENT_NODE_RENDERER";
}
