/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.punchcafe.vngine.gb.newgame;

import java.io.File;
import java.io.IOException;

public class NewProjectGenerator {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        if(args.length != 1){
            throw new IllegalArgumentException();
        }
        final var projectName = args[0];
        if(!projectName.matches("^[a-zA-Z1-9_]+$")){
            throw new RuntimeException();
        }
        final var rootDirectory = new File(projectName);
        rootDirectory.mkdir();
        final var builder = new ProjectBuilder(rootDirectory);
        builder.generate();
    }
}
