/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.punchcafe.gbvng.cli;

import java.util.List;

public class App {

    private final List<CliProcess> subProcesses = List.of(new CodegenAdaptor(), new NewGameAdaptor());
    private final CliProcess rootDelegator = new DelegatorProcess(null, subProcesses);

    public static void main(String[] args) {
        new App().rootDelegator.run(args);
    }
}
